//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Email.
        /// </summary>
        public static string AcademicEmail {
            get {
                return ResourceManager.GetString("AcademicEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string ArUSur {
            get {
                return ResourceManager.GetString("ArUSur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Results.
        /// </summary>
        public static string CourseResults {
            get {
                return ResourceManager.GetString("CourseResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course View.
        /// </summary>
        public static string CourseView {
            get {
                return ResourceManager.GetString("CourseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Hours.
        /// </summary>
        public static string CreditHours {
            get {
                return ResourceManager.GetString("CreditHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor View.
        /// </summary>
        public static string DoctorView {
            get {
                return ResourceManager.GetString("DoctorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events &amp; Activities.
        /// </summary>
        public static string EventsActivities {
            get {
                return ResourceManager.GetString("EventsActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA.
        /// </summary>
        public static string GPA {
            get {
                return ResourceManager.GetString("GPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hub for all student services, events, and materials.
        /// </summary>
        public static string Home_SubTitle {
            get {
                return ResourceManager.GetString("Home-SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Student Affairs System.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Services.
        /// </summary>
        public static string MedicalServices {
            get {
                return ResourceManager.GetString("MedicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Certification.
        /// </summary>
        public static string Military {
            get {
                return ResourceManager.GetString("Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter course name.
        /// </summary>
        public static string P_Course {
            get {
                return ResourceManager.GetString("P-Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string P_Email {
            get {
                return ResourceManager.GetString("P-Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your major.
        /// </summary>
        public static string P_Major {
            get {
                return ResourceManager.GetString("P-Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mobile.
        /// </summary>
        public static string P_Mobile {
            get {
                return ResourceManager.GetString("P-Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string P_Name {
            get {
                return ResourceManager.GetString("P-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anything you like to mention....
        /// </summary>
        public static string P_Survey {
            get {
                return ResourceManager.GetString("P-Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Request.
        /// </summary>
        public static string PreRequest {
            get {
                return ResourceManager.GetString("PreRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your satisfaction (1 to 10).
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Doctors.
        /// </summary>
        public static string RegisteredDoctors {
            get {
                return ResourceManager.GetString("RegisteredDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Students.
        /// </summary>
        public static string RegisteredStudents {
            get {
                return ResourceManager.GetString("RegisteredStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Report.
        /// </summary>
        public static string RegistrationReport {
            get {
                return ResourceManager.GetString("RegistrationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Course.
        /// </summary>
        public static string SelectCourse {
            get {
                return ResourceManager.GetString("SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an instructor.
        /// </summary>
        public static string SelectInstructor {
            get {
                return ResourceManager.GetString("SelectInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Semester.
        /// </summary>
        public static string SelectSemester {
            get {
                return ResourceManager.GetString("SelectSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Academic Year.
        /// </summary>
        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Affairs.
        /// </summary>
        public static string StudentAffairs {
            get {
                return ResourceManager.GetString("StudentAffairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Services.
        /// </summary>
        public static string StudentServices {
            get {
                return ResourceManager.GetString("StudentServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student View.
        /// </summary>
        public static string StudentView {
            get {
                return ResourceManager.GetString("StudentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        public static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the course content is up-to-date?.
        /// </summary>
        public static string Survey_Content {
            get {
                return ResourceManager.GetString("Survey-Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the course live up to your expectations?.
        /// </summary>
        public static string Survey_Expectation {
            get {
                return ResourceManager.GetString("Survey-Expectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How was the Instructor?.
        /// </summary>
        public static string Survey_Instructor {
            get {
                return ResourceManager.GetString("Survey-Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How was the Lap?.
        /// </summary>
        public static string Survey_Lap {
            get {
                return ResourceManager.GetString("Survey-Lap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other comments.
        /// </summary>
        public static string Survey_Others {
            get {
                return ResourceManager.GetString("Survey-Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Experience:.
        /// </summary>
        public static string Survey_Overall {
            get {
                return ResourceManager.GetString("Survey-Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback helps us improve..
        /// </summary>
        public static string SurveyTitle {
            get {
                return ResourceManager.GetString("SurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Students.
        /// </summary>
        public static string TotalStudents {
            get {
                return ResourceManager.GetString("TotalStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age can&apos;t be empty.
        /// </summary>
        public static string V_AgeEmpty {
            get {
                return ResourceManager.GetString("V-AgeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age can&apos;t be larger than {ComparisonValue}.
        /// </summary>
        public static string V_AgeLarge {
            get {
                return ResourceManager.GetString("V-AgeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age can&apos;t be less than {ComparisonValue}.
        /// </summary>
        public static string V_AgeLess {
            get {
                return ResourceManager.GetString("V-AgeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course must be selected.
        /// </summary>
        public static string V_Course {
            get {
                return ResourceManager.GetString("V-Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Hours can&apos;t be empty.
        /// </summary>
        public static string V_CreditHoursEmpty {
            get {
                return ResourceManager.GetString("V-CreditHoursEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Hours can&apos;t be larger than {ComparisonValue}.
        /// </summary>
        public static string V_CreditHoursLarge {
            get {
                return ResourceManager.GetString("V-CreditHoursLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Hours can&apos;t be negative.
        /// </summary>
        public static string V_CreditHoursNegative {
            get {
                return ResourceManager.GetString("V-CreditHoursNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can&apos;t be empty.
        /// </summary>
        public static string V_EmailEmpty {
            get {
                return ResourceManager.GetString("V-EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email ({PropertyValue}) has been registered.
        /// </summary>
        public static string V_EmailExists {
            get {
                return ResourceManager.GetString("V-EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyValue} is not a valid email address.
        /// </summary>
        public static string V_EmailValid {
            get {
                return ResourceManager.GetString("V-EmailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA can&apos;t be empty.
        /// </summary>
        public static string V_GPAEmpyt {
            get {
                return ResourceManager.GetString("V-GPAEmpyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA can&apos;t be larger than {ComparisonValue}.
        /// </summary>
        public static string V_GPALarge {
            get {
                return ResourceManager.GetString("V-GPALarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA can&apos;t be negative.
        /// </summary>
        public static string V_GPANegative {
            get {
                return ResourceManager.GetString("V-GPANegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor must be selected.
        /// </summary>
        public static string V_Instructor {
            get {
                return ResourceManager.GetString("V-Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major can&apos;t be empty.
        /// </summary>
        public static string V_MajorEmpty {
            get {
                return ResourceManager.GetString("V-MajorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Length({TotalLength}) must be between 2 and 150.
        /// </summary>
        public static string V_MajorLength {
            get {
                return ResourceManager.GetString("V-MajorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile can&apos;t be empty.
        /// </summary>
        public static string V_MobileEmpty {
            get {
                return ResourceManager.GetString("V-MobileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile use invalid characters.
        /// </summary>
        public static string V_MobileValid {
            get {
                return ResourceManager.GetString("V-MobileValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty.
        /// </summary>
        public static string V_NameEmpty {
            get {
                return ResourceManager.GetString("V-NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Length({TotalLength}) must be between 3 and 50.
        /// </summary>
        public static string V_NameLength {
            get {
                return ResourceManager.GetString("V-NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreRequest must be a valid course or set to None..
        /// </summary>
        public static string V_PreRequest {
            get {
                return ResourceManager.GetString("V-PreRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester must be selected.
        /// </summary>
        public static string V_Semester {
            get {
                return ResourceManager.GetString("V-Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year must be selected.
        /// </summary>
        public static string V_YearEmpty {
            get {
                return ResourceManager.GetString("V-YearEmpty", resourceCulture);
            }
        }
    }
}
